### ISSUE TITLE
Text in Dropdown List not working.

### ISSUE THREAD

**Issue by 12christiaan** [fvanroie/hasp-lvgl#16]
I have a dropdown list configured. like this.

{"comment":"---------- Page 2 ----------"}
{"objid":50,"id":6,"page":2,"x":10,"y":150,"w":150,"txt":"\uf007 Option A\n\uf007 Option B\n\uf007 Option C"}

I was expecting the text in drop down to be in TXT, but it always show Option 1, Option 2, Option 3.
![screenshot-option](https://user-images.githubusercontent.com/251693/97787522-11ffba00-1bb3-11eb-90d2-3e19b124de30.jpg)

**Comment by arovak** [comment]
That is because the response will be in the `txt` field when you select an option on the display like this `{"p[2].b[6].txt":" Option B"}`
To setup the dropdown list use `options` instead of `txt`

`{"objid":50,"id":6,"page":2,"x":10,"y":150,"w":150,"options":"\uf007 Option A\n\uf007 Option B\n\uf007 Option C"}`

![afbeelding](https://user-images.githubusercontent.com/56759291/97789746-26e44980-1bc3-11eb-9fca-29240c5c7dfa.png)

**Comment by fvanroie** [comment]
Indeed, it should be `options` instead of `txt` when defining the list.
The example `pages.jsonl on the wiki was not correct. I have updated the wiki page.

**Comment by fvanroie** [comment]
@12christiaan Does it work when you use the `options` parameter instead of `txt`?

**Comment by fvanroie** [comment]
I will close this issue due to inactivity. If you still experience this issue, feel free to comment below.
